---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: api-service
  name: api-service
  namespace: webpage
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: api-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: webpage
data:
  config.json: |
    {
      "openWeatherIconUrl": "https://openweathermap.org/img/wn/{}@2x.png",
      "openWeatherUrl": "https://api.openweathermap.org/data/2.5/onecall",
      "goodMorningEmails": [
        {
          "name": "Keith",
          "email": "keith@keithm.io",
          "timezone": "America/New_York",
          "location": {
            "name": "Durham, NC",
            "latitude": 35.995931,
            "longitude": -78.899109
          }
        }
      ]
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: webpage
  labels:
    app: api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
      containers:
        - name: api
          image: registry.gitlab.com/kamackay/api:latest
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8080"
          resources:
              limits:
                cpu: 1000m
                memory: 500Mi
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
          volumeMounts:
            - name: creds
              mountPath: /api/creds.json
              subPath: creds.json
            - name: config-file
              mountPath: /api/config.json
              subPath: config.json
            - name: twittercreds
              mountPath: /api/twitter4j.properties
              subPath: twitter4j.properties
      volumes:
        - name: config-file
          configMap:
            name: api-config
        - name: creds
          secret:
            secretName: creds
        - name: twittercreds
          secret:
            secretName: twitter-creds
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: db
  name: db
  namespace: webpage
spec:
  type: ClusterIP
  ports:
    - name: db
      port: 27017
      targetPort: 27017
  selector:
    service: db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /api/storage
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: webpage
spec:
  serviceName: db
  replicas: 1
  selector:
    matchLabels:
      service: db
  template:
    metadata:
      labels:
        service: db
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - name: db
              containerPort: 27017
          volumeMounts:
            - name: db
              mountPath: /data/db
  volumeClaimTemplates:
    - spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      metadata:
        name: db
---
