---
apiVersion: v1
kind: Namespace
metadata:
  name: webpage
---
apiVersion: v1
kind: Service
metadata:
  name: webpage-service
  namespace: webpage
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: webpage-service
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: webpage
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: api-service
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: webpage
  namespace: webpage
  labels:
    app: webpage-service
spec:
  selector:
    matchLabels:
      app: webpage-service
  template:
    metadata:
      labels:
        app: webpage-service
    spec:
      restartPolicy: Always
      containers:
        - name: webpage
          image: kamackay/webpage:1.0.15
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8080"
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 1
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            limits:
              memory: 10M
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: webpage
  labels:
    app: api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      restartPolicy: Always
      containers:
        - name: api
          image: kamackay/api:latest
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8080"
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
          volumeMounts:
            - name: creds
              mountPath: /api/creds.json
              subPath: creds.json
      volumes:
        - name: creds
          secret:
            secretName: creds
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: db
  name: db
  namespace: webpage
spec:
  type: ClusterIP
  ports:
    - name: db
      port: 27017
      targetPort: 27017
  selector:
    service: db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /api/storage
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: webpage
spec:
  serviceName: db
  replicas: 1
  selector:
    matchLabels:
      service: db
  template:
    metadata:
      labels:
        service: db
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - name: db
              containerPort: 27017
          volumeMounts:
            - name: db
              mountPath: /data/db
  volumeClaimTemplates:
    - spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      metadata:
        name: db
---

