---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webpage-ingress
  namespace: webpage
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-nginx"
spec:
  tls:
    - hosts:
        - keithmackay.com
        - api.keithmackay.com
        - go-api.keithmackay.com
      secretName: cert-secret
  rules:
    - host: keith.mackay.codes
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: webpage-service
                port:
                  number: 8080
    - host: keithmackay.com
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: webpage-service
                port:
                  number: 8080
    - host: api.keithmackay.com
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: api-service
                port:
                  number: 8080
    - host: go-api.keithmackay.com
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: go-api-service
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: io-ingress
  namespace: webpage
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-nginx"
spec:
  tls:
    - hosts:
        - keith.sh
        - keithm.io
        - go.keithm.io
        - api.keithm.io
        - go.keith.sh
        - api.keith.sh
      secretName: io-cert-secret
  rules:
    - host: keith.sh
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: webpage-service
                port:
                  number: 8080
    - host: keithm.io
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: webpage-service
                port:
                  number: 8080
    - host: api.keithm.io
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: api-service
                port:
                  number: 8080
    - host: go.keithm.io
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: go-api-service
                port:
                  number: 8080
    - host: api.keith.sh
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: api-service
                port:
                  number: 8080
    - host: go.keith.sh
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: go-api-service
                port:
                  number: 8080
---
